# Lab - Introduction to NumPy

## 1. Import the NumPy package under the name np

In [35]:
import numpy as np
from IPython.display import Latex

## 2. Print the NumPy version and the configuration

In [3]:
print(np.__version__)
print(np.show_config())

1.15.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fred/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fred/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fred/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fred/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fred/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fred/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fred/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/fred/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/fred/anaconda3/lib']
    define_macros

## 3. Generate a 2x3x5 3-dimensional array with random values.
## Assign the array to variable "a" Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
a = np.random.random((2, 3, 5))

## 4. Print a

In [5]:
print(a)

[[[0.87460122 0.539841   0.02084874 0.55074298 0.14670756]
  [0.5424662  0.49272222 0.64030985 0.80152741 0.97042533]
  [0.06841341 0.08990002 0.63238161 0.25012216 0.96658452]]

 [[0.88094887 0.9014059  0.4532697  0.95472811 0.61264508]
  [0.860857   0.5092282  0.63871966 0.11080657 0.59326195]
  [0.62175003 0.53538051 0.88952979 0.9017931  0.85710612]]]


## 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b"

In [6]:
b = np.ones((5, 2, 3))

## 6. Print b

In [7]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 7. Do a and b have the same size? How do you prove that in Python code?

In [8]:
isEqualArray = np.array_equal(a, b)
print(isEqualArray)

False


## 8. Are you able to add a and b? Why or why not?

In [29]:
if isEqualArray:
    sumAB = np.add(a, b)
    print(sumAB)
else:
    print("No. Arrays a and b are of unequal shapes, and therefore cannot be added")

No. Arrays a and b are of unequal shapes, and therefore cannot be added


## 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [25]:
b.shape
c = np.reshape(b, (2, 3, 5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [87]:
d = np.add(a, c)
print(d, "\n\nAddition works since both arrays are of the same shape.")

[[[1.87460122 1.539841   1.02084874 1.55074298 1.14670756]
  [1.5424662  1.49272222 1.64030985 1.80152741 1.97042533]
  [1.06841341 1.08990002 1.63238161 1.25012216 1.96658452]]

 [[1.88094887 1.9014059  1.4532697  1.95472811 1.61264508]
  [1.860857   1.5092282  1.63871966 1.11080657 1.59326195]
  [1.62175003 1.53538051 1.88952979 1.9017931  1.85710612]]] 

Addition works since both arrays are of the same shape.


## 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [86]:
print(a, d, "\n\nb was comprised of all ones, therefore adding a to b(sup)T = c added 1 to each of the values in a.")

[[[0.87460122 0.539841   0.02084874 0.55074298 0.14670756]
  [0.5424662  0.49272222 0.64030985 0.80152741 0.97042533]
  [0.06841341 0.08990002 0.63238161 0.25012216 0.96658452]]

 [[0.88094887 0.9014059  0.4532697  0.95472811 0.61264508]
  [0.860857   0.5092282  0.63871966 0.11080657 0.59326195]
  [0.62175003 0.53538051 0.88952979 0.9017931  0.85710612]]] [[[1.87460122 1.539841   1.02084874 1.55074298 1.14670756]
  [1.5424662  1.49272222 1.64030985 1.80152741 1.97042533]
  [1.06841341 1.08990002 1.63238161 1.25012216 1.96658452]]

 [[1.88094887 1.9014059  1.4532697  1.95472811 1.61264508]
  [1.860857   1.5092282  1.63871966 1.11080657 1.59326195]
  [1.62175003 1.53538051 1.88952979 1.9017931  1.85710612]]] 

b was comprised of all ones, therefore adding a to b(sup)T = c added 1 to each of the values in a.


## 12. Multiply a and c. Assign the result to e.

In [85]:
e =  np.multiply(a, c)
print(e)

[[[0.87460122 0.539841   0.02084874 0.55074298 0.14670756]
  [0.5424662  0.49272222 0.64030985 0.80152741 0.97042533]
  [0.06841341 0.08990002 0.63238161 0.25012216 0.96658452]]

 [[0.88094887 0.9014059  0.4532697  0.95472811 0.61264508]
  [0.860857   0.5092282  0.63871966 0.11080657 0.59326195]
  [0.62175003 0.53538051 0.88952979 0.9017931  0.85710612]]]


## 13. Does e equal to a? Why or why not?


## 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [77]:
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)
print("min: {}\nmax: {}\nmean: {}".format(d_min, d_max, d_mean))

min: 1.0208487356235925
max: 1.9704253252889354
mean: 1.5969674930007005


## 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [52]:
f = np.empty((2, 3, 5))

## 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f. If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. If a value equals to d_mean, assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f for d_min in d. Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the following values: 0, 25, 50, 75, and 100. Note: you don't have to use Numpy in this question.

In [91]:
f[(d > d_min)&(d < d_mean)] = 25
f[(d > d_mean)&(d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100
f

array([[[ 75.,  25.,   0.,  25.,  25.],
        [ 25.,  25.,  75.,  75., 100.],
        [ 25.,  25.,  75.,  25.,  75.]],

       [[ 75.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  75.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]]])

## 17. Print d and f. Do you have your expected f?

In [94]:
print(d) # Yes
print(f)

[[[1.87460122 1.539841   1.02084874 1.55074298 1.14670756]
  [1.5424662  1.49272222 1.64030985 1.80152741 1.97042533]
  [1.06841341 1.08990002 1.63238161 1.25012216 1.96658452]]

 [[1.88094887 1.9014059  1.4532697  1.95472811 1.61264508]
  [1.860857   1.5092282  1.63871966 1.11080657 1.59326195]
  [1.62175003 1.53538051 1.88952979 1.9017931  1.85710612]]]
[[[ 75.  25.   0.  25.  25.]
  [ 25.  25.  75.  75. 100.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 75.  25.  75.  75.  75.]]]


## 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements? 

In [102]:
g = np.empty((2, 3, 5), dtype = str)
g[(d > d_min)&(d < d_mean)] = "B"
g[(d > d_mean)&(d < d_max)] = "D"
g[d == d_mean] = "C"
g[d == d_min] = "A"
g[d == d_max] = "E"
g


array([[['D', 'B', 'A', 'B', 'B'],
        ['B', 'B', 'D', 'D', 'E'],
        ['B', 'B', 'D', 'B', 'D']],

       [['D', 'D', 'B', 'D', 'D'],
        ['D', 'B', 'D', 'B', 'B'],
        ['D', 'B', 'D', 'D', 'D']]], dtype='<U1')