In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.__version__)
print(np.show_config())

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

#4. Print a.

print(a)

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

z = np.random.random((5,2,3))
b = z/z

#6. Print b.

print(b)

#7. Do a and b have the same size? How do you prove that in Python code?

a == b


#8. Are you able to add a and b? Why or why not?

print('No, they do not have the same size')

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.reshape(2,3,5)
print(c)
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a+c
print(d, 'because they re the same shape')

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print('\n\n\n\n',a,'\n\n',d,'\nArray d has 1 added to it..')


#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)

#13. Does e equal to a? Why or why not?

e == a
print('when you multiply a number by 1, you get that same number')



1.15.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:31: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.


In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min =np.min(d)
d_mean =np.mean(d)

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
print(f,"\n\n\n\n")


# """
## #16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
## If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
## If a value equals to d_mean, assign 50 to the corresponding value in f.
## Assign 0 to the corresponding value(s) in f for d_min in d.
## Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
# """

I,J,K = 0,0,0

for outer in d: 

    for mid in outer: 
        
        for i in range(len(mid)): 
            if mid[i] > d_min and mid[i] < d_mean: 
                f[I,J,K] = 25
            if mid[i] > d_mean and mid[i] < d_max: 
                f[I,J,K] = 75
            if mid[i] == d_mean: 
                f[I,J,K] = 50 
            if mid[i] == d_min: 
                f[I,J,K] = 0 
            if mid[i] == d_max: 
                f[I,J,K] = 100 
                
            K += 1
        J += 1 
        K=0
    I += 1
    J = 0 
    K= 0
    
print(f)
            
            
        



# """
# #17. Print d and f. Do you have your expected f?
# For instance, if your d is:
# array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#         [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#         [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

#        [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#         [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#         [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Your f should be:
# array([[[ 75.,  75.,  75.,  25.,  75.],
#         [ 75.,  75.,  25.,  25.,  25.],
#         [ 75.,  25.,  75.,  75.,  75.]],

#        [[ 25.,  25.,  25.,  25., 100.],
#         [ 75.,  75.,  75.,  75.,  75.],
#         [ 25.,  75.,   0.,  75.,  75.]]])
# """

print('yes')




[[[6.88767966e-042 1.59956915e+160 3.40659570e-057 1.52182487e-051
   5.01163190e+217]
  [5.49419094e-143 9.80058441e+252 1.04857885e-142 2.14027814e+161
   1.38789905e+219]
  [3.30076751e+180 1.35617292e+248 9.13135035e-072 1.55175299e+184
   2.65188212e-052]]

 [[8.69366941e-043 7.11767518e-144 1.16097020e-028 1.10685158e-047
   2.26166296e-076]
  [1.91823489e-076 1.11763122e+261 1.16318408e-028 2.15398318e-308
   6.94890404e-310]
  [9.58487353e-322 0.00000000e+000 0.00000000e+000 0.00000000e+000
   5.02034658e+175]]] 




[[[ 75.  25.  75.  25.  75.]
  [ 25. 100.  75.  75.  25.]
  [ 25.  75.  75.   0.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]]]
yes


In [15]:
# """
# #18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],

#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.
# """
d_max = np.max(d)
d_min =np.min(d)
d_mean =np.mean(d)
I,J,K = 0,0,0
A = np.full((2,3,5),'')

for outer in d: 

    for mid in outer: 
        
        for i in range(len(mid)): 
            if mid[i] > d_min and mid[i] < d_mean: 
                A[I,J,K] = 'D'
            if mid[i] > d_mean and mid[i] < d_max: 
                A[I,J,K] = 'B'
            if mid[i] == d_mean: 
                A[I,J,K] = 'A'
            if mid[i] == d_min: 
                A[I,J,K] = 'C'
            if mid[i] == d_max: 
                A[I,J,K] = 'E' 
                
            K += 1
        J += 1 
        K=0
    I += 1
    J = 0 
    K= 0
    
print(A)


[[['B' 'D' 'B' 'D' 'B']
  ['D' 'E' 'B' 'B' 'D']
  ['D' 'B' 'B' 'C' 'D']]

 [['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'B' 'D']]]
