In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.16.2


In [2]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))

#a=np.random.normal((2,3,5))
#a=np.random.uniform((2,3,5))
#4. Print a.
print(a)

[[[0.44597035 0.08870119 0.99952177 0.29940306 0.23359335]
  [0.39382337 0.40599397 0.99751225 0.65090027 0.23986147]
  [0.62729486 0.42412377 0.66827961 0.07313626 0.45887253]]

 [[0.86108245 0.88695666 0.43269916 0.14779845 0.66699515]
  [0.35446085 0.90370837 0.3330465  0.78654807 0.64206586]
  [0.87540562 0.50229934 0.09560188 0.22117585 0.14984954]]]


In [8]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))


#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
#7. Do a and b have the same size? How do you prove that in Python code?
#yes, shown below:
print(a.size)
print(b.size)


#8. Are you able to add a and b? Why or why not?
#no - not same shape

30
30


In [17]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".
c=np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [19]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=np.add(a, c)
print(d)
#it works now because they are the same size (2,3,5)


#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
#both a and d have the same size and shape, but d is "1" larger than a due to the addition function done in question 10

[[[1.44597035 1.08870119 1.99952177 1.29940306 1.23359335]
  [1.39382337 1.40599397 1.99751225 1.65090027 1.23986147]
  [1.62729486 1.42412377 1.66827961 1.07313626 1.45887253]]

 [[1.86108245 1.88695666 1.43269916 1.14779845 1.66699515]
  [1.35446085 1.90370837 1.3330465  1.78654807 1.64206586]
  [1.87540562 1.50229934 1.09560188 1.22117585 1.14984954]]]
[[[0.44597035 0.08870119 0.99952177 0.29940306 0.23359335]
  [0.39382337 0.40599397 0.99751225 0.65090027 0.23986147]
  [0.62729486 0.42412377 0.66827961 0.07313626 0.45887253]]

 [[0.86108245 0.88695666 0.43269916 0.14779845 0.66699515]
  [0.35446085 0.90370837 0.3330465  0.78654807 0.64206586]
  [0.87540562 0.50229934 0.09560188 0.22117585 0.14984954]]]


In [21]:
#12. Multiply a and c. Assign the result to e.
e=np.multiply(a, c)
print(e)


#13. Does e equal to a? Why or why not?
print(a) #it does because multiplying by one (matrix c) gives the original value

[[[0.44597035 0.08870119 0.99952177 0.29940306 0.23359335]
  [0.39382337 0.40599397 0.99751225 0.65090027 0.23986147]
  [0.62729486 0.42412377 0.66827961 0.07313626 0.45887253]]

 [[0.86108245 0.88695666 0.43269916 0.14779845 0.66699515]
  [0.35446085 0.90370837 0.3330465  0.78654807 0.64206586]
  [0.87540562 0.50229934 0.09560188 0.22117585 0.14984954]]]
[[[0.44597035 0.08870119 0.99952177 0.29940306 0.23359335]
  [0.39382337 0.40599397 0.99751225 0.65090027 0.23986147]
  [0.62729486 0.42412377 0.66827961 0.07313626 0.45887253]]

 [[0.86108245 0.88695666 0.43269916 0.14779845 0.66699515]
  [0.35446085 0.90370837 0.3330465  0.78654807 0.64206586]
  [0.87540562 0.50229934 0.09560188 0.22117585 0.14984954]]]


In [64]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.amax(d)
d_min=np.amin(d)
d_mean=np.mean(d)



#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) 
#as d using `np.empty`.
f=np.empty(shape=(2,3,5))
print(f)
print(d_min)

[[[ 25.  25. 100.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  75.   0.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]]]
1.0731362589715085


In [32]:
#16. Populate the values in f. For each value in d, 
#if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.



[1.44597035 1.08870119 1.99952177 1.29940306 1.23359335]
[1.39382337 1.40599397 1.99751225 1.65090027 1.23986147]
[1.62729486 1.42412377 1.66827961 1.07313626 1.45887253]


In [62]:
I,J,K=0,0,0
for i in d:
    for j in i:
        for k in range(len(j)):
            if j[k] > d_min and d_mean > j[k]:
                f[I,J,K]= 25
            elif j[k] > d_mean and d_max > j[k]:
                   f[I,J,K] = 75
            elif j[k] == d_mean:
                f[I,J,K] = 50
            elif j[k] == d_min:
                f[I,J,K] = 0
            elif j[k] == d_max:
                f[I,J,K] = 100
            K=K+1
        K=0
        J+=1
    K=0
    J=0
    I+=1
print(f)
            

[[[ 25.  25. 100.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  75.   0.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]]]


In [63]:
#17. Print d and f. Do you have your expected f? Yes, it makes sense.
print(d)
print(f)

[[[1.44597035 1.08870119 1.99952177 1.29940306 1.23359335]
  [1.39382337 1.40599397 1.99751225 1.65090027 1.23986147]
  [1.62729486 1.42412377 1.66827961 1.07313626 1.45887253]]

 [[1.86108245 1.88695666 1.43269916 1.14779845 1.66699515]
  [1.35446085 1.90370837 1.3330465  1.78654807 1.64206586]
  [1.87540562 1.50229934 1.09560188 1.22117585 1.14984954]]]
[[[ 25.  25. 100.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  75.   0.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]]]


In [68]:
#18. 
#Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be: 
