In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.2


In [3]:
print(np.show_config())

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/regi_/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/regi_/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/regi_/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

In [4]:
a = np.random.random((2,3,5))
print(a)

[[[0.61681318 0.5910209  0.67601799 0.25537516 0.47981783]
  [0.280159   0.50775764 0.17804969 0.41116406 0.8620068 ]
  [0.48354813 0.07577686 0.55025047 0.13853183 0.85380872]]

 [[0.29744698 0.42880875 0.94750196 0.5701038  0.91706079]
  [0.88631947 0.32218788 0.2326092  0.74446881 0.53186933]
  [0.27012724 0.57105879 0.80066506 0.36534311 0.50386688]]]


In [5]:
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
print(a.size)
print(b.size)

30
30


In [7]:
# yes, sizes are the same

In [8]:
# no, you cannot add a and be because they have different shapes.
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


In [9]:
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
print(c.shape)

(2, 3, 5)


In [11]:
# we can add a and c now because it has the same shape now. 2x3x5
d = np.add(a, c)
print(d)

[[[1.61681318 1.5910209  1.67601799 1.25537516 1.47981783]
  [1.280159   1.50775764 1.17804969 1.41116406 1.8620068 ]
  [1.48354813 1.07577686 1.55025047 1.13853183 1.85380872]]

 [[1.29744698 1.42880875 1.94750196 1.5701038  1.91706079]
  [1.88631947 1.32218788 1.2326092  1.74446881 1.53186933]
  [1.27012724 1.57105879 1.80066506 1.36534311 1.50386688]]]


In [12]:
print(a)

[[[0.61681318 0.5910209  0.67601799 0.25537516 0.47981783]
  [0.280159   0.50775764 0.17804969 0.41116406 0.8620068 ]
  [0.48354813 0.07577686 0.55025047 0.13853183 0.85380872]]

 [[0.29744698 0.42880875 0.94750196 0.5701038  0.91706079]
  [0.88631947 0.32218788 0.2326092  0.74446881 0.53186933]
  [0.27012724 0.57105879 0.80066506 0.36534311 0.50386688]]]


In [13]:
print(d)

[[[1.61681318 1.5910209  1.67601799 1.25537516 1.47981783]
  [1.280159   1.50775764 1.17804969 1.41116406 1.8620068 ]
  [1.48354813 1.07577686 1.55025047 1.13853183 1.85380872]]

 [[1.29744698 1.42880875 1.94750196 1.5701038  1.91706079]
  [1.88631947 1.32218788 1.2326092  1.74446881 1.53186933]
  [1.27012724 1.57105879 1.80066506 1.36534311 1.50386688]]]


In [14]:
# the relation between the a and d is the difference between their values of 1. since the d was a sum of a and c(array of ones)


In [15]:
e = np.multiply(a, c)
print(e)

[[[0.61681318 0.5910209  0.67601799 0.25537516 0.47981783]
  [0.280159   0.50775764 0.17804969 0.41116406 0.8620068 ]
  [0.48354813 0.07577686 0.55025047 0.13853183 0.85380872]]

 [[0.29744698 0.42880875 0.94750196 0.5701038  0.91706079]
  [0.88631947 0.32218788 0.2326092  0.74446881 0.53186933]
  [0.27012724 0.57105879 0.80066506 0.36534311 0.50386688]]]


In [16]:
# yes, e equals to a because we multiplied the elements of array a by ones

In [17]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9475019558846138
1.0757768583394753
1.5116512106303233


In [18]:
#Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
print(f)

[[[0.61681318 0.5910209  0.67601799 0.25537516 0.47981783]
  [0.280159   0.50775764 0.17804969 0.41116406 0.8620068 ]
  [0.48354813 0.07577686 0.55025047 0.13853183 0.85380872]]

 [[0.29744698 0.42880875 0.94750196 0.5701038  0.91706079]
  [0.88631947 0.32218788 0.2326092  0.74446881 0.53186933]
  [0.27012724 0.57105879 0.80066506 0.36534311 0.50386688]]]


In [19]:
for x in range(len(d)):
    for y in range(len(d[0])):
        for i in range(len(d[0][0])):
            if d[x][y][i] > d_min and d[x][y][i] < d_mean:
                f[x][y][i] = 25
            if d[x][y][i] > d_mean and d[x][y][i] < d_max:
                f[x][y][i] = 75
            if d[x][y][i] == d_mean:
                f[x][y][i] = 50
            if d[x][y][i] == d_min:
                f[x][y][i] = 0
            if d[x][y][i] == d_max:
                f[x][y][i] = 100
print(f)

[[[ 75.  75.  75.  25.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 25.   0.  75.  25.  75.]]

 [[ 25.  25. 100.  75.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]]]


In [20]:
print(d)

[[[1.61681318 1.5910209  1.67601799 1.25537516 1.47981783]
  [1.280159   1.50775764 1.17804969 1.41116406 1.8620068 ]
  [1.48354813 1.07577686 1.55025047 1.13853183 1.85380872]]

 [[1.29744698 1.42880875 1.94750196 1.5701038  1.91706079]
  [1.88631947 1.32218788 1.2326092  1.74446881 1.53186933]
  [1.27012724 1.57105879 1.80066506 1.36534311 1.50386688]]]


In [24]:
new_d = np.full((2,3,5), " ")
print(new_d)
for x in range(len(d)):
    for y in range(len(d[0])):
        for i in range(len(d[0][0])):
            if d[x][y][i] > d_min and d[x][y][i] < d_mean:
                new_d[x][y][i] = "A"
            if d[x][y][i] > d_mean and d[x][y][i] < d_max:
                new_d[x][y][i] = "B"
            if d[x][y][i] == d_mean:
                new_d[x][y][i] = "C"
            if d[x][y][i] == d_min:
                new_d[x][y][i] = "D"
            if d[x][y][i] == d_max:
                new_d[x][y][i] = "E"
print(new_d)

[[[' ' ' ' ' ' ' ' ' ']
  [' ' ' ' ' ' ' ' ' ']
  [' ' ' ' ' ' ' ' ' ']]

 [[' ' ' ' ' ' ' ' ' ']
  [' ' ' ' ' ' ' ' ' ']
  [' ' ' ' ' ' ' ' ' ']]]
[[['B' 'B' 'B' 'A' 'A']
  ['A' 'A' 'A' 'A' 'B']
  ['A' 'D' 'B' 'A' 'B']]

 [['A' 'A' 'E' 'B' 'B']
  ['B' 'A' 'A' 'B' 'B']
  ['A' 'B' 'B' 'A' 'A']]]
