In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

#2. Print the NUMPY version and the configuration.
print(np.__version__)

1.16.4


In [2]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

#4. Print a.
print(a)

[[[4.46895429e-01 5.86570952e-01 5.25180947e-01 2.50174330e-01
   9.59845380e-01]
  [6.63733638e-01 9.35818752e-01 3.65291131e-02 7.39621600e-01
   1.71829578e-01]
  [6.65152204e-01 1.59917260e-01 7.67480452e-01 3.69096382e-01
   2.49794791e-01]]

 [[3.29978898e-01 4.87250555e-01 7.33830862e-01 9.43006707e-05
   2.02060735e-01]
  [8.68940863e-01 1.95350132e-01 6.08945255e-01 3.32462858e-01
   6.83850757e-01]
  [5.40549288e-01 5.82779531e-01 8.93491428e-01 7.73590190e-01
   2.57202481e-01]]]


In [3]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.full((5,2,3), 1)

#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [4]:
#7. Do a and b have the same size? How do you prove that in Python code?
if a.size == b.size:
    print (True)
else:
    print (False)

True


In [5]:
#8. Are you able to add a and b? Why or why not?
try:
    print(np.add(a,b))
except:
    print("You cannot add arrays, unless they have the same dimension")

You cannot add arrays, unless they have the same dimension


In [6]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [7]:
#10. Try to add a and c. Now it should work.
# Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print(d)
# This works now because the arrays have the same dimensions

[[[1.44689543 1.58657095 1.52518095 1.25017433 1.95984538]
  [1.66373364 1.93581875 1.03652911 1.7396216  1.17182958]
  [1.6651522  1.15991726 1.76748045 1.36909638 1.24979479]]

 [[1.3299789  1.48725056 1.73383086 1.0000943  1.20206073]
  [1.86894086 1.19535013 1.60894525 1.33246286 1.68385076]
  [1.54054929 1.58277953 1.89349143 1.77359019 1.25720248]]]


In [8]:
#11. Print a and d.
# Notice the difference and relation of the two array in terms of the values? Explain.
print(a, "\n\n")
print(d)
# d is just the same as a, but all values are incremented by 1

[[[4.46895429e-01 5.86570952e-01 5.25180947e-01 2.50174330e-01
   9.59845380e-01]
  [6.63733638e-01 9.35818752e-01 3.65291131e-02 7.39621600e-01
   1.71829578e-01]
  [6.65152204e-01 1.59917260e-01 7.67480452e-01 3.69096382e-01
   2.49794791e-01]]

 [[3.29978898e-01 4.87250555e-01 7.33830862e-01 9.43006707e-05
   2.02060735e-01]
  [8.68940863e-01 1.95350132e-01 6.08945255e-01 3.32462858e-01
   6.83850757e-01]
  [5.40549288e-01 5.82779531e-01 8.93491428e-01 7.73590190e-01
   2.57202481e-01]]] 


[[[1.44689543 1.58657095 1.52518095 1.25017433 1.95984538]
  [1.66373364 1.93581875 1.03652911 1.7396216  1.17182958]
  [1.6651522  1.15991726 1.76748045 1.36909638 1.24979479]]

 [[1.3299789  1.48725056 1.73383086 1.0000943  1.20206073]
  [1.86894086 1.19535013 1.60894525 1.33246286 1.68385076]
  [1.54054929 1.58277953 1.89349143 1.77359019 1.25720248]]]


In [9]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)
print(e)
#13. Does e equal to a? Why or why not?
# Yes it does, because 1*x = x and array c only has values of "1"

[[[4.46895429e-01 5.86570952e-01 5.25180947e-01 2.50174330e-01
   9.59845380e-01]
  [6.63733638e-01 9.35818752e-01 3.65291131e-02 7.39621600e-01
   1.71829578e-01]
  [6.65152204e-01 1.59917260e-01 7.67480452e-01 3.69096382e-01
   2.49794791e-01]]

 [[3.29978898e-01 4.87250555e-01 7.33830862e-01 9.43006707e-05
   2.02060735e-01]
  [8.68940863e-01 1.95350132e-01 6.08945255e-01 3.32462858e-01
   6.83850757e-01]
  [5.40549288e-01 5.82779531e-01 8.93491428e-01 7.73590190e-01
   2.57202481e-01]]]


In [10]:
#14. Identify the max, min, and mean values in d.
# Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9598453798666293 1.000094300670745 1.5006006314057452


In [11]:
#15. Now we want to label the values in d.
# First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))

In [15]:
#16. Populate the values in f.
# For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
for i in range(len(d)):
    print (i)
    for j in range(len(d[0])):
        for k in range(len(d[0][0])):
            x = d[i][j][k]
            if x > d_min and x < d_mean:
                f[i][j][k] = 25
            elif x > d_mean and x < d_max:
                f[i][j][k] = 75
            elif x == d_mean:
                f[i][j][k] = 50
            elif x == d_min:
                f[i][j][k] = 0
            elif x == d_max:
                f[i][j][k] = 100
            #print(d[i][j][k])
print (f)

0
1
[[[ 25.  25.  75.  25.  25.]
  [ 75.  25. 100.  25.  75.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.   0.  75.  25.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]]]


In [13]:
#17. Print d and f. Do you have your expected f?
print(d, "\n\n")
print(f)

[[[1.44689543 1.58657095 1.52518095 1.25017433 1.95984538]
  [1.66373364 1.93581875 1.03652911 1.7396216  1.17182958]
  [1.6651522  1.15991726 1.76748045 1.36909638 1.24979479]]

 [[1.3299789  1.48725056 1.73383086 1.0000943  1.20206073]
  [1.86894086 1.19535013 1.60894525 1.33246286 1.68385076]
  [1.54054929 1.58277953 1.89349143 1.77359019 1.25720248]]] 


[[[ 25.  75.  75.  25. 100.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  25.  75.  25.  25.]]

 [[ 25.  25.  75.   0.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  75.  75.  25.]]]


In [14]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100),
# how to use string values ("A", "B", "C", "D", and "E") to label the array elements? 
g = np.full((2,3,5), "")
for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0][0])):
            x = d[i][j][k]
            if x > d_min and x < d_mean:
                g[i][j][k] = "B"
            elif x > d_mean and x < d_max:
                g[i][j][k] = "D"
            elif x == d_mean:
                g[i][j][k] = "C"
            elif x == d_min:
                g[i][j][k] = "A"
            elif x == d_max:
                g[i][j][k] = "E"
print(g)

[[['B' 'D' 'D' 'B' 'E']
  ['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'B']]

 [['B' 'B' 'D' 'A' 'B']
  ['D' 'B' 'D' 'B' 'D']
  ['D' 'D' 'D' 'D' 'B']]]
