# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

# Challenge 1 - Matrix Functions

#### We would like to create our own matrix. To make life simple for us, we can represent matrices as a list of lists. For the sake of simplicity, we will assume that the maximum number of dimensions a matrix will have is 2.

The most basic thing we would like to do with two matrices is to add them together. To add two matrices, we must perform a number of checks. The first check we would like to perform is whether the matrix is two dimesional. This is because we want to limit ourselves to two dimensional matrices to simplify our problem. In the cell below write a function that checks is a matrix is two dimesional. 

In [3]:
import numpy as np

def twodim(mat):
    if (type(mat) is not list):
        raise ValueError("Error: Variable is not list.")
    for x in mat:
        if (type(x) is not list):
            raise ValueError("Error: Variable is not two dimensional")
        for y in x:
            if (type(y) is list):
                raise ValueError("Error: Matrix is more than two dimensional")
    return("TRUE")

    # This function takes a list of lists and checks that it is of depth 2. 
    # If the depth is not 2, either return false or return informative errors that let the user know the depth of the list.
    # Input: nested list
    # Output: Boolean (or error)
    # Sample Input: [[1,2,3], [4,5,6]]
    # Sample Output: True
    
    # Your Code Here:mat = np.array([[1,2], [1,2,3],[1,2,3]])
    

In [4]:
twodim([[1,2], [1,2,3],[1,2,3]])

'TRUE'

# Bonus Challenge 1 - Write the function recursively

Rewrite the `twodim` function using recursion. 
Read more about recursion [here](https://www.cs.utah.edu/~germain/PPS/Topics/recursion.html)

Hint: stop your recursion when there are no more lists, this wil be the depth of your matrix. Check that this depth is equal to 2.
Second Hint: At every level of the recursion, use the filter function to keep only the members of the list that are lists.

In [5]:

def twodimrecursive(mat):
    if not type(mat) == list:
        return("FALSE")
    else:
        l = len(mat)
        if (l <= 2):
            print("Depth is 2")
        else:
            print("Depth is not 2")
    # Your code here:
    
    
    

In [6]:
twodimrecursive([[1,2,3],[1,2]])

Depth is 2


#### Next, we will write a function that checks for the number of rows and columns of a matrix. 

Recall that the outer list will tell us the number of rows and the inner lists will tell us the number of columns. Make sure that all inner lists are of the same length.

In [7]:
import numpy as np

    
def rowcolumn(mat):
        print(np.shape(mat))

    
    # This function takes a list of lists and returns the size of the rows and the columns 
    # Input: list of lists
    # Output: Tuple of rows and columns
    #
    # Sample input: [[1,2,3],[4,5,6]]
    # Sample Output: (2, 3)
    
    # Your code here:
    

In [8]:
rowcolumn([[1,2,3,4], [1,2,3,4],[1,2,3,4]])

(3, 4)


In [9]:
def rowcolumn(mat):
    rows = len(mat)
    cols = len(mat[0])
    print((rows,cols))

In [10]:
rowcolumn([[1,2,3,4], [1,2,3,4],[1,2,3,4]])

(3, 4)


#### Our next step is to write a function that compares two matrices and tells us whether they are of equal size.

In this function we will check whether the number of rows and number of columns is the same.

In [11]:
def compare(mat1, mat2):
    print(np.shape(mat1))
    print(np.shape(mat2))
    if np.shape(mat1) == np.shape(mat2):
        print("TRUE")
    else:
        print("FALSE")
    # This function takes a two lists of lists and checks whether they have the same number of rows and columns
    # Input: two list of lists
    # Output: True or False
    #
    # Sample input: [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
    # Sample Output: True
    
    # Your code here:
    

In [12]:
compare([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]])

(2, 3)
(2, 3)
TRUE


#### Now that we have all the tools we need, write a function that adds two matrices together. 

Remember that a matrix is represented as a list of lists. Therefore, we must add each element in the list. The plus symbol is used for concatenating two lists and not for adding every element in two lists.

In [13]:
import numpy as np
result=np.zeros((2,3)) #need to specify dimensions before before filling in empty list
def addition(mat1, mat2):
    print(mat1)
    print(mat2)
    for i in range(len(mat1)):
        for j in range(len(mat1[0])):
            result[i][j]=mat1[i][j]+mat2[i][j]
 
    print(result)
    # This function takes a two lists of lists and adds each cell together
    # Input: two list of lists
    # Output: one summed list of lists
    #
    # Sample input: [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
    # Sample Output: [[8,10,12],[14,16,18]]
    
    # Your code here:
    

In [14]:
a = [[1,2,3],[4,5,6]]
a[0][0]

1

In [15]:
addition([[1,2,3],
          [4,5,6]], 
         
         [[7,8,9], 
          [10,11,12]])

[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[ 8. 10. 12.]
 [14. 16. 18.]]


# Challenge 2 - Creating the Class

In the cell below, you will be creating the class Matrix2D. Use the functions you have written above and tweak them according to the instructions in the comments. You got this!

In [16]:
class Matrix2D:
    # First, we will write the __init__ function. 
    # In this function, we will initialize rows and the columns using the matrix that we have passed to the class.

    def __init__(self, mat):
        self.mat = mat
        self.rows = rowcolumn(self.mat)
        self.cols = rowcolumn(self.mat)
        # Assign mat to self.mat
        # Assign rows and cols to self.rows and self.cols
        # To find the rows and the cols, use the rowcolumn function and pass self.mat to the function.
        # Since the rowcolumn function is now a member of the class, make sure to refer to the function as self.rowcolumn
        
        # Your code here:
 
 
    def rowcolumn(self, mat):
        self.rows=len(self.mat)
        self.cols = len(self.mat[0])
        print((self.rows,self.cols))
    # Insert the twodim function here.
    # The only change you need to make is that now we are passing self and mat to the function (make sure self is first).
    
    # Your code here:
    def twodim(self,mat):
        if (type(self.mat) is not list):
            raise ValueError("Error: Variable is not list.")
        for x in self.mat:
            if (type(x) is not list):
                raise ValueError("Error: Variable is not two dimensional")
            for y in x:
                if (type(y) is list):
                    raise ValueError("Error: Matrix is more than two dimensional")
        return("TRUE")

    
    # Insert the rowcolumn function here.
    # The changes you need to make: 
    # 1. The function now takes self and mat as arguments (make sure to pass self first).
    # 2. Any reference to twodim will be changed to self.twodim since this function is a member of the class and takes self 
    
    # Your code here:

    
    
    # Insert the compare function here
    # Add self as the first argument passed to the function

    # Your code here:
    def compare(self, matrix):
        rows = len(self.mat)
        cols=len(self.mat[0])
        rows1=len(matrix.mat)
        cols1=len(matrix.mat[0])
        if (rows, cols) == (rows1,cols1):
            print("TRUE")
        else:
            print("FALSE")


    # Insert the addition function here
    # This function now takes self and matrix (another matrix of the Matrix2D class)
    # Change the compare function to self.compare 
    # Change any reference to mat1 and mat2 to self.mat and matrix.mat respectively
    # Return your result as a Matrix2D(result). This will ensure that we return a new matrix and not a list of lists.
    
    # Your code here:
   #need to specify dimensions before before filling in empty list
    def addition(self, matrix):
        print(self.mat)
        print(matrix.mat)
        for i in range(len(self.mat)):
            for j in range(len(self.mat[0])):
                result[i][j]=self.mat[i][j]+matrix.mat[i][j]
        return(result)

In [17]:
Matrix2D([[1,2,3],[4,5,6]]).addition(Matrix2D([[7,8,9],[10,11,12]]))

(2, 3)
(2, 3)
(2, 3)
(2, 3)
[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]


array([[ 8., 10., 12.],
       [14., 16., 18.]])

# Bonus Challenge 2 - Transpose Function

#### Write a function that transposes the matrix and add it to your class.

You can read more about the transpose of a matrix [here](https://en.wikipedia.org/wiki/Transpose).

Hint: Use the zip function. Read about it [here](https://docs.python.org/3.3/library/functions.html#zip)

Second Hint: Read about the asterisk in Python [here](https://docs.python.org/3/reference/expressions.html#expression-lists)

In [1]:
import numpy as np



    
def transpose(mat):
    np.transpose(mat)
    print(np.transpose(mat))
    # This function takes a list of lists and returns a transposed list of lists.
    # Input: list of lists
    # Output: list of lists
   
    # Sample Input: [[1,2,3],[4,5,6]]
    # Sample Output: [[1,4], [2,5], [3,6]]
  
    # Your code here:
    

In [2]:
transpose([[1,2,3],[4,5,6]])

[[1 4]
 [2 5]
 [3 6]]
